export const TestData = [
  { name: "Test 1", value: 1, status: "done" },
  { name: "Test 2", value: 2, status: "done" },
  { name: "Test 3", value: 3, status: "done" },
  { name: "Test 4", value: 4, status: "done" },
  { name: "Test 5", value: 5, status: "done" },
  { name: "Test 6", value: 6, status: "done" },
  { name: "Test 7", value: 7, status: "done" },
  { name: "Test 8", value: 8, status: "done" },
  { name: "Test 9", value: 9, status: "done" },
  { name: "Test 10", value: 10, status: "done" },
  { name: "Test 11", value: 11, status: "done" },
  { name: "Test 12", value: 12, status: "done" },
  { name: "Test 13", value: 13, status: "done" },
  { name: "Test 14", value: 14, status: "done" },
  { name: "Test 15", value: 15, status: "done" },
  { name: "Test 16", value: 16, status: "done" },
];
